In [1]:
# 读取本地鸢尾花数据，并给列名
import pandas as pd
PATH = './'
df = pd.read_csv(PATH+'iris.data',names=['sepal length','sepal width','petal length','petal width', 'class'])

In [2]:
df.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
# 按class分组,平均
df.groupby("class").mean()

                 sepal length  sepal width  petal length  petal width
class
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [4]:
# 按class分组,描述
df.groupby("class").describe()

                sepal length                                              \
                       count   mean       std  min    25%  50%  75%  max
class
Iris-setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                sepal width         ... petal length      petal width         \
                      count   mean  ...          75%  max       count   mean
class                               ...
Iris-setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
Iris-versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
Iris-virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                      std  min  25%  50%  75%  max
class
Iris-setosa      0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [7]:
df.groupby('petal width')['class'].unique().to_frame()

                                         class
petal width
0.1                              [Iris-setosa]
0.2                              [Iris-setosa]
0.3                              [Iris-setosa]
0.4                              [Iris-setosa]
0.5                              [Iris-setosa]
0.6                              [Iris-setosa]
1.0                          [Iris-versicolor]
1.1                          [Iris-versicolor]
1.2                          [Iris-versicolor]
1.3                          [Iris-versicolor]
1.4          [Iris-versicolor, Iris-virginica]
1.5          [Iris-versicolor, Iris-virginica]
1.6          [Iris-versicolor, Iris-virginica]
1.7          [Iris-versicolor, Iris-virginica]
1.8          [Iris-versicolor, Iris-virginica]
1.9                           [Iris-virginica]
2.0                           [Iris-virginica]
2.1                           [Iris-virginica]
2.2                           [Iris-virginica]
2.3                           [Iris-virginica]
2.4                           [Iris-virginica]
2.5                           [Iris-virginica]